#
# ATTENTION! BEFORE YOU SEED, MAKE SURE YOUR TABLE IS COMPLETELY EMPTY
# IF YOU WANT TO RESET AUTOINCREMENT VALUE, HERE IS THE COMMAND
# delete from sqlite_sequence where name='courses';
# COMMENT OUT THE COMMAND ONCE YOU ARE DONE PLEASE
#

#Computer Science
Course.create(department: 'Computer Science', course_id: '31', professor_last_name: 'Smallberg', professor_first_name: 'David')
Course.create(department: 'Computer Science', course_id: '32', professor_last_name: 'Smallberg', professor_first_name: 'David')
Course.create(department: 'Computer Science', course_id: '32', professor_last_name: 'Nachenberg', professor_first_name: 'Carey')
Course.create(department: 'Computer Science', course_id: '33', professor_last_name: 'Reinman', professor_first_name: 'Glenn')
Course.create(department: 'Computer Science', course_id: '33', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '35L', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: 'M51A', professor_last_name: 'He', professor_first_name: 'Yutao')
Course.create(department: 'Computer Science', course_id: 'M51A', professor_last_name: 'Potkonjak', professor_first_name: 'Miodrag')
Course.create(department: 'Computer Science', course_id: 'M51A', professor_last_name: 'Srivastava', professor_first_name: 'Mani')
Course.create(department: 'Computer Science', course_id: '97', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: '111', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '111', professor_last_name: 'Reiher', professor_first_name: 'Peter')
Course.create(department: 'Computer Science', course_id: '112', professor_last_name: 'Sanadid', professor_first_name: 'Medy')
Course.create(department: 'Computer Science', course_id: '114', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M117', professor_last_name: 'Gerla', professor_first_name: 'Mario')
Course.create(department: 'Computer Science', course_id: 'M117', professor_last_name: 'Dzhanidze', professor_first_name: 'Revaz')
Course.create(department: 'Computer Science', course_id: '118', professor_last_name: 'Gerla', professor_first_name: 'Mario')
Course.create(department: 'Computer Science', course_id: '118', professor_last_name: 'Zhang', professor_first_name: 'Lixia')
Course.create(department: 'Computer Science', course_id: 'CM121', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM122', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM124', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: '130', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '131', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '131', professor_last_name: 'Millstein', professor_first_name: 'Todd')
Course.create(department: 'Computer Science', course_id: '132', professor_last_name: 'Palsberg', professor_first_name: 'Jens')
Course.create(department: 'Computer Science', course_id: '133', professor_last_name: 'Cong', professor_first_name: 'Jason')
Course.create(department: 'Computer Science', course_id: '136', professor_last_name: 'Reiher', professor_first_name: 'Peter')
Course.create(department: 'Computer Science', course_id: '143', professor_last_name: 'Cho', professor_first_name: 'Junghoo')
Course.create(department: 'Computer Science', course_id: '144', professor_last_name: 'Cho', professor_first_name: 'Junghoo')
Course.create(department: 'Computer Science', course_id: '145', professor_last_name: 'Wang', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M151B', professor_last_name: 'Tamir', professor_first_name: 'Yuval')
Course.create(department: 'Computer Science', course_id: '151C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M152A', professor_last_name: 'Potkonjak', professor_first_name: 'Miodrag')
Course.create(department: 'Computer Science', course_id: '152B', professor_last_name: 'Sarrafzadeh', professor_first_name: 'Majid')
Course.create(department: 'Computer Science', course_id: '161', professor_last_name: 'Darwiche', professor_first_name: 'Adnan')
Course.create(department: 'Computer Science', course_id: '161', professor_last_name: 'Dyer', professor_first_name: 'Michael')
Course.create(department: 'Computer Science', course_id: '170A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M171L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: '174A', professor_last_name: 'Friedman', professor_first_name: 'Scott')
Course.create(department: 'Computer Science', course_id: '174B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'C174C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: '180', professor_last_name: 'Sarrafzadeh', professor_first_name: 'Majid')
Course.create(department: 'Computer Science', course_id: '181', professor_last_name: 'Sherstov', professor_first_name: 'Alexander')
Course.create(department: 'Computer Science', course_id: '183', professor_last_name: 'Ostrovsky', professor_first_name: 'Rafail')
Course.create(department: 'Computer Science', course_id: 'M184', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM186', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM187', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: '188', professor_last_name: 'Mutz', professor_first_name: 'Andrew')

#Bioengineering
Course.create(department: 'Bioengineering', course_id: '10', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '100', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C101', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM102', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM103', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C104', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C105', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C106', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C107', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '110', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '120', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C131', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C139A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C139B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM140', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM145', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C147', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM150', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM150L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C155', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '165EW', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '167L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C170', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C170L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C171', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C172', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '176', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '177A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '177B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM178', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C179', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '180', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '180L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C183', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'M184', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'C185', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM186', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: 'CM187', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '188', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '194', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Bioengineering', course_id: '199', professor_last_name: '', professor_first_name: '')

#Chemical and Biomelecular Engineering
Course.create(department: 'Chemical Engineering', course_id: '2', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '10', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '100', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '101A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '101B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '101C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '102A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '102B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '103', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '104A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '104B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '104C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '104CL', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '104D', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '104DL', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '106', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '107', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '108A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '108B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '109', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '110', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C111', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C112', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '113', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C114', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C115', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C116', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C118', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C119', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C121', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C124', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C125', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'CM127', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C128', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C135', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'C140', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: 'CM145', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '188', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '194', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Chemical Engineering', course_id: '199', professor_last_name: '', professor_first_name: '')

#Civil and Environmental
Course.create(department: 'Civil and Environmental', course_id: '1', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '15', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: 'M20', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '58SL', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '85', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '97', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '101', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '103', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: 'C104', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '108', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '110', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '120', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '121', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '123', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '125', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '128L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '129L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '130', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '130L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '135A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '135B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: 'M135C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '135L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '137', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '137L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '140L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '141', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '142', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '142L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '143', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '144', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '147', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '150', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '151', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '152', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '153', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '154', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '155', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '156A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '156B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '157A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '157B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '157C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '157L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '157M', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '163', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '164', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: 'M165', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: 'M166', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: 'M166L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '180', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '181', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: 'C182', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '188', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '192', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '194', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Civil and Environmental', course_id: '199', professor_last_name: '', professor_first_name: '')

#Materials SCience and Engineering
Course.create(department: 'Materials Science and Engineering', course_id: '10', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '90L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '104', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: 'M105', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '110', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '110L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: 'C111', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: 'C112', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '120', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '121', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '121L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '122', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '130', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '131', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '131L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '132', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: 'C133', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '140', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '141L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '143A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '143L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '150', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '151', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '160', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '161', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '161L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '162', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '170', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '171', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: 'CM180', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '188', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '194', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Materials Science and Engineering', course_id: '199', professor_last_name: '', professor_first_name: '')

#Mechanical and Aerospace Engineering Courses
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '15', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'M20', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '94', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '101', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '102', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '103', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '105A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '105D', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '107', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '131A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C132A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '133A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '135', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '136', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C137', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'CM140', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '150A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '150B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '150C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C150G', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C150P', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C150R', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '153A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '154A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '154B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '154S', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '155', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '156A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C156B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '157', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '157A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '157S', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '161A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '161B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '161C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '161D', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '162A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '162D', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '162E', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '166A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '166C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'M168', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '169A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '171A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '171B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '172', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '174', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C175A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'CM180', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'CM180L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '181A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '182A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '182B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '182C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '183', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '184', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '185', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C186', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: 'C187L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '188', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '194', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Mechanical and Aerospacece Engineering', course_id: '199', professor_last_name: '', professor_first_name: '')

#Electrical Engineering
Course.create(department: 'Electrical Engineering', course_id: '2', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '3', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '10', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '11L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'M16', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '100', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '101A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '101B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '102', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '110', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '110L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '111L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '113', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '113DA-113DB', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '114', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '115A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '115AL', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '115B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '115BL', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '115C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '115D', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'M116C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'M116L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'M117', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '121B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '121DA-121DB', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '122L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '123A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '123B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '128', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '131A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '131B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '132A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '132B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '133A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '133B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '141', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '142', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'CM150', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '150DL', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'CM150L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '162A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '163A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '163C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '164DA-164DB', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '164L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '170A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '170B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '170C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '170L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'M171L', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '173DA-173DB', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '174', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '176', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '180DA-180DB', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '181D', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'CM182', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '183DA-183DB', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '184DA-184DB', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: 'M185', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '188', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '194', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Electrical Engineering', course_id: '199', professor_last_name: '', professor_first_name: '')

user = User.create! :email => 'admin@admin.com', :password => 'admin1234', :password_confirmation => 'admin1234', :first_name => 'admin', :last_name => 'admin', :courses_taken => "Computer Science 31, Computer Science 32", :admin => true
# Document.create([{path: '/CS31/COM_SCI_31_Unknown_2010_Fall_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2010_Fall'}, {path: '/CS32/COM_SCI_32_Nachenberg_2012_Winter_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2012_Winter'}, {path: '/CS32/COM_SCI_32_Smallberg_2007_Winter_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2007_Winter'}])
# Document.create([{path: '/CS33/COM_SCI_33_Reinman_2009_Spring_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2009_Spring'}, {path: '/CS33/COM_SCI_33_Reinman_2010_Spring_MT_1.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2010_Spring'}, {path: '/CS33/COM_SCI_33_Rohr_2008_Fall_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2008_Fall'}])

