#
# ATTENTION! BEFORE YOU SEED, MAKE SURE YOUR TABLE IS COMPLETELY EMPTY
# IF YOU WANT TO RESET AUTOINCREMENT VALUE, HERE IS THE COMMAND
# delete from sqlite_sequence where name='courses';
# COMMENT OUT THE COMMAND ONCE YOU ARE DONE PLEASE
#

#Computer Science
Course.create(department: 'Computer Science', course_id: '31', professor_last_name: 'Smallberg', professor_first_name: 'David')
Course.create(department: 'Computer Science', course_id: '32', professor_last_name: 'Smallberg', professor_first_name: 'David')
Course.create(department: 'Computer Science', course_id: '32', professor_last_name: 'Nachenberg', professor_first_name: 'Carey')
Course.create(department: 'Computer Science', course_id: '33', professor_last_name: 'Reinman', professor_first_name: 'Glenn')
Course.create(department: 'Computer Science', course_id: '33', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '35L', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: 'M51A', professor_last_name: 'He', professor_first_name: 'Yutao')
Course.create(department: 'Computer Science', course_id: 'M51A', professor_last_name: 'Potkonjak', professor_first_name: 'Miodrag')
Course.create(department: 'Computer Science', course_id: 'M51A', professor_last_name: 'Srivastava', professor_first_name: 'Mani')
Course.create(department: 'Computer Science', course_id: '97', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: '111', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '111', professor_last_name: 'Reiher', professor_first_name: 'Peter')
Course.create(department: 'Computer Science', course_id: '112', professor_last_name: 'Sanadid', professor_first_name: 'Medy')
Course.create(department: 'Computer Science', course_id: '114', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M117', professor_last_name: 'Gerla', professor_first_name: 'Mario')
Course.create(department: 'Computer Science', course_id: 'M117', professor_last_name: 'Dzhanidze', professor_first_name: 'Revaz')
Course.create(department: 'Computer Science', course_id: '118', professor_last_name: 'Gerla', professor_first_name: 'Mario')
Course.create(department: 'Computer Science', course_id: '118', professor_last_name: 'Zhang', professor_first_name: 'Lixia')
Course.create(department: 'Computer Science', course_id: 'CM121', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM122', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM124', professor_last_name: 'Eskin', professor_first_name: 'Eleazer')
Course.create(department: 'Computer Science', course_id: '130', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '130', professor_last_name: 'Kim', professor_first_name: 'Miryung')
Course.create(department: 'Computer Science', course_id: '131', professor_last_name: 'Eggert', professor_first_name: 'Paul')
Course.create(department: 'Computer Science', course_id: '131', professor_last_name: 'Millstein', professor_first_name: 'Todd')
Course.create(department: 'Computer Science', course_id: '132', professor_last_name: 'Palsberg', professor_first_name: 'Jens')
Course.create(department: 'Computer Science', course_id: '133', professor_last_name: 'Cong', professor_first_name: 'Jason')
Course.create(department: 'Computer Science', course_id: '136', professor_last_name: 'Reiher', professor_first_name: 'Peter')
Course.create(department: 'Computer Science', course_id: '143', professor_last_name: 'Cho', professor_first_name: 'Junghoo')
Course.create(department: 'Computer Science', course_id: '144', professor_last_name: 'Cho', professor_first_name: 'Junghoo')
Course.create(department: 'Computer Science', course_id: '145', professor_last_name: 'Wang', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M151B', professor_last_name: 'Tamir', professor_first_name: 'Yuval')
Course.create(department: 'Computer Science', course_id: '151C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M152A', professor_last_name: 'Potkonjak', professor_first_name: 'Miodrag')
Course.create(department: 'Computer Science', course_id: '152B', professor_last_name: 'Sarrafzadeh', professor_first_name: 'Majid')
Course.create(department: 'Computer Science', course_id: '161', professor_last_name: 'Darwiche', professor_first_name: 'Adnan')
Course.create(department: 'Computer Science', course_id: '161', professor_last_name: 'Dyer', professor_first_name: 'Michael')
Course.create(department: 'Computer Science', course_id: '170A', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'M171L', professor_last_name: 'Dzhanidze', professor_first_name: 'Revaz P.')
Course.create(department: 'Computer Science', course_id: '174A', professor_last_name: 'Friedman', professor_first_name: 'Scott')
Course.create(department: 'Computer Science', course_id: '174B', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'C174C', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: '180', professor_last_name: 'Sarrafzadeh', professor_first_name: 'Majid')
Course.create(department: 'Computer Science', course_id: '181', professor_last_name: 'Sherstov', professor_first_name: 'Alexander')
Course.create(department: 'Computer Science', course_id: '183', professor_last_name: 'Ostrovsky', professor_first_name: 'Rafail')
Course.create(department: 'Computer Science', course_id: 'M184', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM186', professor_last_name: '', professor_first_name: '')
Course.create(department: 'Computer Science', course_id: 'CM187', professor_last_name: 'Distefano', professor_first_name: 'Joseph')
Course.create(department: 'Computer Science', course_id: '188', professor_last_name: 'Mutz', professor_first_name: 'Andrew')
Course.create(department: 'Computer Science', course_id: '188', professor_last_name: 'Ford', professor_first_name: 'Diana')

#Bioengineering
Course.create(department: 'Bioengineering', course_id: '110', professor_last_name: 'Kamei', professor_first_name: 'Daniel')
Course.create(department: 'Bioengineering', course_id: 'C131', professor_last_name: 'Schmidt', professor_first_name: 'Jacob')
Course.create(department: 'Bioengineering', course_id: 'C139B', professor_last_name: 'Wong', professor_first_name: 'Gerard')
Course.create(department: 'Bioengineering', course_id: 'C147', professor_last_name: 'Tawil', professor_first_name: 'Bill')
Course.create(department: 'Bioengineering', course_id: 'C155', professor_last_name: 'di Carlo', professor_first_name: 'Dino')
Course.create(department: 'Bioengineering', course_id: '167L', professor_last_name: 'Liang', professor_first_name: 'Jesse')
Course.create(department: 'Bioengineering', course_id: 'C172', professor_last_name: 'Grundfest', professor_first_name: 'Warren')
Course.create(department: 'Bioengineering', course_id: '176', professor_last_name: 'Wu', professor_first_name: 'Ben')
Course.create(department: 'Bioengineering', course_id: '180L', professor_last_name: 'Dunn', professor_first_name: 'James')
Course.create(department: 'Bioengineering', course_id: 'C183', professor_last_name: 'Kasko', professor_first_name: 'Andrea')
Course.create(department: 'Bioengineering', course_id: 'CM187', professor_last_name: 'Distefano', professor_first_name: 'Joseph')
Course.create(department: 'Bioengineering', course_id: '224B', professor_last_name: 'Arnold', professor_first_name: 'Corey')
Course.create(department: 'Bioengineering', course_id: 'M225', professor_last_name: 'Segura', professor_first_name: 'Tatiana')
Course.create(department: 'Bioengineering', course_id: 'M226', professor_last_name: 'Taira', professor_first_name: 'Ricky')
Course.create(department: 'Bioengineering', course_id: 'C231', professor_last_name: 'Schmidt', professor_first_name: 'Jacob')
Course.create(department: 'Bioengineering', course_id: 'M233B', professor_last_name: 'Liu', professor_first_name: 'Wentai')
Course.create(department: 'Bioengineering', course_id: 'C239B', professor_last_name: 'Wong', professor_first_name: 'Gerard')
Course.create(department: 'Bioengineering', course_id: 'C247', professor_last_name: 'Tawil', professor_first_name: 'Bill')
Course.create(department: 'Bioengineering', course_id: 'M250B', professor_last_name: 'Candler', professor_first_name: 'Robert')
Course.create(department: 'Bioengineering', course_id: 'C255', professor_last_name: 'di Carlo', professor_first_name: 'Dino')
Course.create(department: 'Bioengineering', course_id: 'C272', professor_last_name: 'Grundfest', professor_first_name: 'Warren')
Course.create(department: 'Bioengineering', course_id: 'C283', professor_last_name: 'Kasko', professor_first_name: 'Andrea')
Course.create(department: 'Bioengineering', course_id: 'CM287', professor_last_name: 'Distefano', professor_first_name: 'Joseph')
Course.create(department: 'Bioengineering', course_id: '295A', professor_last_name: 'Kasko', professor_first_name: 'Andrea')
Course.create(department: 'Bioengineering', course_id: '295B', professor_last_name: 'Wu', professor_first_name: 'Ben')
Course.create(department: 'Bioengineering', course_id: '295D', professor_last_name: 'Schmidt', professor_first_name: 'Jacob')
Course.create(department: 'Bioengineering', course_id: '295E', professor_last_name: 'Kamei', professor_first_name: 'Daniel')
Course.create(department: 'Bioengineering', course_id: '295F', professor_last_name: 'Deming', professor_first_name: 'Timothy')
Course.create(department: 'Bioengineering', course_id: '298', professor_last_name: 'Deming', professor_first_name: 'Timothy')
Course.create(department: 'Bioengineering', course_id: '299', professor_last_name: 'Kasko', professor_first_name: 'Andrea')

#Chemical And Biomelecular Engineering
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '101C', professor_last_name: 'Cohen', professor_first_name: 'Yoram')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '102B', professor_last_name: 'Lu', professor_first_name: 'Yunfeng')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '103', professor_last_name: 'Senkan', professor_first_name: 'Selim')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '104A', professor_last_name: 'Grasel', professor_first_name: 'Timothy')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '104B', professor_last_name: 'Simonetti', professor_first_name: 'Dante A.')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '108B', professor_last_name: 'Gerek Ince', professor_first_name: 'Zeynep Nevin')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: 'C125', professor_last_name: 'Segura', professor_first_name: 'Tatiana')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: 'C128', professor_last_name: 'Olmos', professor_first_name: 'Fernando')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: 'C135', professor_last_name: 'Christofides', professor_first_name: 'Panagiotis D.')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '194', professor_last_name: 'Manousiouthakis', professor_first_name: 'Vasilios')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: 'CM225', professor_last_name: 'Segura', professor_first_name: 'Tatiana')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: 'C228', professor_last_name: 'Manousiouthakis', professor_first_name: 'Vasilios')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: 'C235', professor_last_name: 'Christofides', professor_first_name: 'Panagiotis D.')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '298A', professor_last_name: 'Christofides', professor_first_name: 'Panagiotis D.')
Course.create(department: 'Chemical And Biomolecular Engineering', course_id: '299', professor_last_name: 'Chen', professor_first_name: 'Yvonne Y.')

#Civil And Environmental
Course.create(department: 'Civil And Environmental Engineering', course_id: '19', professor_last_name: 'Jay', professor_first_name: 'Jennifer A.')
Course.create(department: 'Civil And Environmental Engineering', course_id: 'M20', professor_last_name: 'Taciroglu', professor_first_name: 'Ertugrul')
Course.create(department: 'Civil And Environmental Engineering', course_id: '103', professor_last_name: 'Ruter', professor_first_name: 'Marcus')
Course.create(department: 'Civil And Environmental Engineering', course_id: '110', professor_last_name: 'Jay', professor_first_name: 'Jennifer A.')
Course.create(department: 'Civil And Environmental Engineering', course_id: '123', professor_last_name: 'Brandenberg', professor_first_name: 'Scott')
Course.create(department: 'Civil And Environmental Engineering', course_id: '128L', professor_last_name: 'Vucetic', professor_first_name: 'Mladen')
Course.create(department: 'Civil And Environmental Engineering', course_id: 'M135C', professor_last_name: 'Klug', professor_first_name: 'William')
Course.create(department: 'Civil And Environmental Engineering', course_id: '135L', professor_last_name: 'Burton', professor_first_name: 'Henry')
Course.create(department: 'Civil And Environmental Engineering', course_id: '140L', professor_last_name: 'Wallace', professor_first_name: 'John W')
Course.create(department: 'Civil And Environmental Engineering', course_id: '143', professor_last_name: 'Bondy', professor_first_name: 'Dirk')
Course.create(department: 'Civil And Environmental Engineering', course_id: '144', professor_last_name: 'Daniel', professor_first_name: 'Nergal')
Course.create(department: 'Civil And Environmental Engineering', course_id: '152', professor_last_name: 'Kendall', professor_first_name: 'Donald')
Course.create(department: 'Civil And Environmental Engineering', course_id: '156A', professor_last_name: 'Lau', professor_first_name: 'Sim-Lin')
Course.create(department: 'Civil And Environmental Engineering', course_id: 'M165', professor_last_name: 'Mahendra', professor_first_name: 'Shaily')
Course.create(department: 'Civil And Environmental Engineering', course_id: '180', professor_last_name: 'Gibson', professor_first_name: 'Patrick')
Course.create(department: 'Civil And Environmental Engineering', course_id: '194', professor_last_name: 'Sabol', professor_first_name: 'Thomas')
Course.create(department: 'Civil And Environmental Engineering', course_id: '194', professor_last_name: 'Jay', professor_first_name: 'Jennifer A.')
Course.create(department: 'Civil And Environmental Engineering', course_id: '200', professor_last_name: 'Sant', professor_first_name: 'Gaurav')
Course.create(department: 'Civil And Environmental Engineering', course_id: '200', professor_last_name: 'Mahendra', professor_first_name: 'Shaily')
Course.create(department: 'Civil And Environmental Engineering', course_id: '221', professor_last_name: 'Hudson', professor_first_name: 'Martin B.')
Course.create(department: 'Civil And Environmental Engineering', course_id: '225', professor_last_name: 'Stewart', professor_first_name: 'Jonathan P.')
Course.create(department: 'Civil And Environmental Engineering', course_id: '227', professor_last_name: 'Pradel', professor_first_name: 'Daniel E')
Course.create(department: 'Civil And Environmental Engineering', course_id: 'M230C', professor_last_name: 'Ju', professor_first_name: 'Jiann-Wen')
Course.create(department: 'Civil And Environmental Engineering', course_id: '233', professor_last_name: 'Dong', professor_first_name: 'Stanley B.')
Course.create(department: 'Civil And Environmental Engineering', course_id: '241', professor_last_name: 'Sabol', professor_first_name: 'Thomas')
Course.create(department: 'Civil And Environmental Engineering', course_id: '243B', professor_last_name: 'Kim', professor_first_name: 'Sunai')
Course.create(department: 'Civil And Environmental Engineering', course_id: '247', professor_last_name: 'Zhang', professor_first_name: 'Jian')
Course.create(department: 'Civil And Environmental Engineering', course_id: '250D', professor_last_name: 'Yeh', professor_first_name: 'William')
Course.create(department: 'Civil And Environmental Engineering', course_id: '251C', professor_last_name: 'Gebremichael', professor_first_name: 'Mekonnen')
Course.create(department: 'Civil And Environmental Engineering', course_id: '258A', professor_last_name: 'Marambio Jones', professor_first_name: 'Catalina')
Course.create(department: 'Civil And Environmental Engineering', course_id: '261B', professor_last_name: 'Stenstrom', professor_first_name: 'Michael K.')
Course.create(department: 'Civil And Environmental Engineering', course_id: '298', professor_last_name: 'Bauchy', professor_first_name: 'Mathieu')

#Electrical
Course.create(department: 'Electrical Engineering', course_id: '2', professor_last_name: 'Wong', professor_first_name: 'Chee Wei')
Course.create(department: 'Electrical Engineering', course_id: '3', professor_last_name: 'Pottie', professor_first_name: 'Greg')
Course.create(department: 'Electrical Engineering', course_id: 'M16', professor_last_name: 'He', professor_first_name: 'Yutao')
Course.create(department: 'Electrical Engineering', course_id: '101B', professor_last_name: 'Jarrahi', professor_first_name: 'Mona')
Course.create(department: 'Electrical Engineering', course_id: '102', professor_last_name: 'Fragouli', professor_first_name: 'Christina')
Course.create(department: 'Electrical Engineering', course_id: '110', professor_last_name: 'Abidi', professor_first_name: 'Asad A.')
Course.create(department: 'Electrical Engineering', course_id: '110L', professor_last_name: 'Mesghali', professor_first_name: 'Farid')
Course.create(department: 'Electrical Engineering', course_id: '110L', professor_last_name: 'Babaie', professor_first_name: 'Hassan')
Course.create(department: 'Electrical Engineering', course_id: '111L', professor_last_name: 'Babaie', professor_first_name: 'Hassan')
Course.create(department: 'Electrical Engineering', course_id: '112', professor_last_name: 'Habibi Ashrafi', professor_first_name: 'Farrokh')
Course.create(department: 'Electrical Engineering', course_id: '113', professor_last_name: 'van der Schaar', professor_first_name: 'Mihaela')
Course.create(department: 'Electrical Engineering', course_id: '113DB', professor_last_name: 'Briggs', professor_first_name: 'Dennis M.')
Course.create(department: 'Electrical Engineering', course_id: '114', professor_last_name: 'Lorenzelli', professor_first_name: 'Flavio')
Course.create(department: 'Electrical Engineering', course_id: '115A', professor_last_name: 'Darabi', professor_first_name: 'Hooman')
Course.create(department: 'Electrical Engineering', course_id: '115AL', professor_last_name: 'Babaie', professor_first_name: 'Hassan')
Course.create(department: 'Electrical Engineering', course_id: '115AL', professor_last_name: 'Gu', professor_first_name: 'Xuefeng')
Course.create(department: 'Electrical Engineering', course_id: '115C', professor_last_name: 'Yang', professor_first_name: 'C.-K. Ken')
Course.create(department: 'Electrical Engineering', course_id: '115D', professor_last_name: 'Razavi', professor_first_name: 'Behzad')
Course.create(department: 'Electrical Engineering', course_id: 'M116C', professor_last_name: 'Tamir', professor_first_name: 'Yuval')
Course.create(department: 'Electrical Engineering', course_id: 'M116L', professor_last_name: 'Guo', professor_first_name: 'Jia')
Course.create(department: 'Electrical Engineering', course_id: 'M116L', professor_last_name: 'Millar', professor_first_name: 'Matthew')
Course.create(department: 'Electrical Engineering', course_id: 'M116L', professor_last_name: 'Shahmohammadi', professor_first_name: 'Farhad')
Course.create(department: 'Electrical Engineering', course_id: 'M116L', professor_last_name: 'He', professor_first_name: 'Lei')
Course.create(department: 'Electrical Engineering', course_id: 'M116L', professor_last_name: 'Shahbazi', professor_first_name: 'Behnam')
Course.create(department: 'Electrical Engineering', course_id: 'M117', professor_last_name: 'Gerla', professor_first_name: 'Mario')
Course.create(department: 'Electrical Engineering', course_id: '121DB', professor_last_name: 'Chui', professor_first_name: 'Chi On')
Course.create(department: 'Electrical Engineering', course_id: '132A', professor_last_name: 'Dolecek', professor_first_name: 'Lara')
Course.create(department: 'Electrical Engineering', course_id: '133A', professor_last_name: 'Vandenberghe', professor_first_name: 'Lieven')
Course.create(department: 'Electrical Engineering', course_id: '141', professor_last_name: 'Roh', professor_first_name: 'Tae Jung')
Course.create(department: 'Electrical Engineering', course_id: '162A', professor_last_name: 'Rahmat-Samii', professor_first_name: 'Yahya')
Course.create(department: 'Electrical Engineering', course_id: '164DB', professor_last_name: 'Chang', professor_first_name: 'Mau-Chung')
Course.create(department: 'Electrical Engineering', course_id: '170C', professor_last_name: 'Williams', professor_first_name: 'Benjamin')
Course.create(department: 'Electrical Engineering', course_id: 'M171L', professor_last_name: 'Dzhanidze', professor_first_name: 'Revaz P.')
Course.create(department: 'Electrical Engineering', course_id: '176', professor_last_name: 'Ozcan', professor_first_name: 'Aydogan')
Course.create(department: 'Electrical Engineering', course_id: '180DB', professor_last_name: 'Kaiser', professor_first_name: 'William')
Course.create(department: 'Electrical Engineering', course_id: '201D', professor_last_name: 'Gupta', professor_first_name: 'Puneet')
Course.create(department: 'Electrical Engineering', course_id: 'M202B', professor_last_name: 'Srivastava', professor_first_name: 'Mani B.')
Course.create(department: 'Electrical Engineering', course_id: '209AS', professor_last_name: 'Cabric', professor_first_name: 'Danijela')
Course.create(department: 'Electrical Engineering', course_id: '209AS', professor_last_name: 'Chaudhari', professor_first_name: 'Shailesh Digambar')
Course.create(department: 'Electrical Engineering', course_id: '210B', professor_last_name: 'Sayed', professor_first_name: 'Ali H.')
Course.create(department: 'Electrical Engineering', course_id: '214B', professor_last_name: 'Alwan', professor_first_name: 'Abeer')
Course.create(department: 'Electrical Engineering', course_id: '214B', professor_last_name: 'Alwan', professor_first_name: 'Abeer')
Course.create(department: 'Electrical Engineering', course_id: '215D', professor_last_name: 'Moloudi', professor_first_name: 'Shervin')
Course.create(department: 'Electrical Engineering', course_id: '215E', professor_last_name: 'Pamarti', professor_first_name: 'Sudhakar')
Course.create(department: 'Electrical Engineering', course_id: '215E', professor_last_name: 'Hameed', professor_first_name: 'Sameed / Pamarti, Sudhakar')
Course.create(department: 'Electrical Engineering', course_id: '222', professor_last_name: 'Pan', professor_first_name: 'Andrew Samuel / Chui, Chi On')
Course.create(department: 'Electrical Engineering', course_id: '223', professor_last_name: 'Wong', professor_first_name: 'Chee Wei')
Course.create(department: 'Electrical Engineering', course_id: '230B', professor_last_name: 'Chang', professor_first_name: 'Hua-I')
Course.create(department: 'Electrical Engineering', course_id: '230C', professor_last_name: 'Yao', professor_first_name: 'Kung')
Course.create(department: 'Electrical Engineering', course_id: '231E', professor_last_name: 'Wesel', professor_first_name: 'Richard')
Course.create(department: 'Electrical Engineering', course_id: '231E', professor_last_name: 'Wesel', professor_first_name: 'Richard ')
Course.create(department: 'Electrical Engineering', course_id: '232D', professor_last_name: 'Lin', professor_first_name: 'Yu-Yu')
Course.create(department: 'Electrical Engineering', course_id: '232E', professor_last_name: 'Roychowdhury', professor_first_name: 'Vwani')
Course.create(department: 'Electrical Engineering', course_id: 'M250B', professor_last_name: 'Candler', professor_first_name: 'Robert')
Course.create(department: 'Electrical Engineering', course_id: '266', professor_last_name: 'Itoh', professor_first_name: 'Tatsuo')
Course.create(department: 'Electrical Engineering', course_id: '279AS', professor_last_name: 'Joshi', professor_first_name: 'Chandra')
Course.create(department: 'Electrical Engineering', course_id: '295', professor_last_name: 'Watson', professor_first_name: 'Dana Cairns')
Course.create(department: 'Electrical Engineering', course_id: '297', professor_last_name: 'Wang', professor_first_name: 'Kang')
Course.create(department: 'Electrical Engineering', course_id: '299', professor_last_name: 'Abidi', professor_first_name: 'Asad A.')

#Engineering
Course.create(department: 'Engineering', course_id: '96', professor_last_name: 'Stafsudd', professor_first_name: 'John')
Course.create(department: 'Engineering', course_id: 'M103', professor_last_name: 'Mahendra', professor_first_name: 'Shaily')
Course.create(department: 'Engineering', course_id: '110', professor_last_name: 'Bulu-Taciroglu', professor_first_name: 'Meliha')
Course.create(department: 'Engineering', course_id: '112', professor_last_name: 'Grimm', professor_first_name: 'Schaffer')
Course.create(department: 'Engineering', course_id: '120', professor_last_name: 'Farshchi', professor_first_name: 'Shahin')
Course.create(department: 'Engineering', course_id: '180', professor_last_name: 'Kung', professor_first_name: 'Kenneth C')
Course.create(department: 'Engineering', course_id: '183EW', professor_last_name: 'Weltman', professor_first_name: 'Gershon')
Course.create(department: 'Engineering', course_id: '185EW', professor_last_name: 'Silverstein', professor_first_name: 'Robert L.')
Course.create(department: 'Engineering', course_id: '192', professor_last_name: 'Pottie', professor_first_name: 'Greg')
Course.create(department: 'Engineering', course_id: '202', professor_last_name: 'Hecht', professor_first_name: 'Myron Jay')
Course.create(department: 'Engineering', course_id: '299', professor_last_name: 'M\'Closkey', professor_first_name: 'Robert T.')
Course.create(department: 'Engineering', course_id: 'M495B', professor_last_name: 'Rubinson', professor_first_name: 'Gregory')

#Materials Science And Engineering
Course.create(department: 'Materials Science And Engineering', course_id: '90L', professor_last_name: 'Chun', professor_first_name: 'Steven')
Course.create(department: 'Materials Science And Engineering', course_id: '104', professor_last_name: 'Pei', professor_first_name: 'Qibing')
Course.create(department: 'Materials Science And Engineering', course_id: '104', professor_last_name: 'Kodambaka', professor_first_name: 'Suneel')
Course.create(department: 'Materials Science And Engineering', course_id: '121', professor_last_name: 'Huang', professor_first_name: 'Yu')
Course.create(department: 'Materials Science And Engineering', course_id: '121L', professor_last_name: 'Zhang', professor_first_name: 'Wei')
Course.create(department: 'Materials Science And Engineering', course_id: '121L', professor_last_name: 'Zhang', professor_first_name: 'Wei')
Course.create(department: 'Materials Science And Engineering', course_id: '132', professor_last_name: 'Ono', professor_first_name: 'Kanji')
Course.create(department: 'Materials Science And Engineering', course_id: '140', professor_last_name: 'Hiel', professor_first_name: 'Clement')
Course.create(department: 'Materials Science And Engineering', course_id: '151', professor_last_name: 'Yang', professor_first_name: 'Jenn-Ming')
Course.create(department: 'Materials Science And Engineering', course_id: '161L', professor_last_name: 'Trujillo', professor_first_name: 'Joy Elizabeth')
Course.create(department: 'Materials Science And Engineering', course_id: '201', professor_last_name: 'Tu', professor_first_name: 'King-Ning')
Course.create(department: 'Materials Science And Engineering', course_id: '210', professor_last_name: 'Goorsky', professor_first_name: 'Mark S.')
Course.create(department: 'Materials Science And Engineering', course_id: 'C211', professor_last_name: 'Prikhodko', professor_first_name: 'Sergey')
Course.create(department: 'Materials Science And Engineering', course_id: '226', professor_last_name: 'Xie', professor_first_name: 'Ya-Hong')
Course.create(department: 'Materials Science And Engineering', course_id: '246B', professor_last_name: 'Dunn', professor_first_name: 'Bruce')
Course.create(department: 'Materials Science And Engineering', course_id: '248', professor_last_name: 'Yang', professor_first_name: 'Yang')
Course.create(department: 'Materials Science And Engineering', course_id: '282', professor_last_name: 'Huang', professor_first_name: 'Yu')
Course.create(department: 'Materials Science And Engineering', course_id: '298', professor_last_name: 'Mosleh', professor_first_name: 'Ali')
Course.create(department: 'Materials Science And Engineering', course_id: '298', professor_last_name: 'Marian', professor_first_name: 'Jaime')
Course.create(department: 'Materials Science And Engineering', course_id: '298', professor_last_name: 'Ozolins', professor_first_name: 'Vidvuds')
Course.create(department: 'Materials Science And Engineering', course_id: '298', professor_last_name: 'Yang', professor_first_name: 'Jenn-Ming')


#Mechanical
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'M20', professor_last_name: 'Taciroglu', professor_first_name: 'Ertugrul')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '94', professor_last_name: 'Gadh', professor_first_name: 'Rajit')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '101', professor_last_name: 'Chatterjee', professor_first_name: 'Amiya')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '102', professor_last_name: 'Santos', professor_first_name: 'Veronica')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '103', professor_last_name: 'Kim', professor_first_name: 'J. John')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '105A', professor_last_name: 'Abdou', professor_first_name: 'Mohamed')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '107', professor_last_name: 'M\'Closkey', professor_first_name: 'Robert T.')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C132A', professor_last_name: 'Marner', professor_first_name: 'Wilbur J')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '133A', professor_last_name: 'Amar', professor_first_name: 'Ravnesh C.')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '150B', professor_last_name: 'Zhong', professor_first_name: 'Xiaolin')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C150G', professor_last_name: 'Eldredge', professor_first_name: 'Jeff')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C150R', professor_last_name: 'Wirz', professor_first_name: 'Richard')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '154B', professor_last_name: 'Zhou', professor_first_name: 'Zhengliu ')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '156A', professor_last_name: 'Ghoniem', professor_first_name: 'Nasr M.')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '157', professor_last_name: 'Ramirez', professor_first_name: 'Benjamin')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '157A', professor_last_name: 'Kavehpour', professor_first_name: 'Hossein')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '157A', professor_last_name: 'Kavehpour', professor_first_name: 'Hossein')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '157S', professor_last_name: 'Peng', professor_first_name: 'Cheng')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '161C', professor_last_name: 'Goebel', professor_first_name: 'Dan M.')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '162A', professor_last_name: 'Hopkins', professor_first_name: 'Jonathan')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '162E', professor_last_name: 'Kang', professor_first_name: 'Christopher Sunghwa')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'M168', professor_last_name: 'Klug', professor_first_name: 'William')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '171A', professor_last_name: 'Speyer', professor_first_name: 'Jason')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '171B', professor_last_name: 'Tsao', professor_first_name: 'Tsu-Chin')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '171B', professor_last_name: 'Tsao', professor_first_name: 'Tsu-Chin / Bai, Yu')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '182A', professor_last_name: 'Rosen', professor_first_name: 'Jacob')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '182B', professor_last_name: 'Schaal', professor_first_name: 'Christoph A.')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '183', professor_last_name: 'Kim', professor_first_name: 'Chang-Jin')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C186', professor_last_name: 'Chiou', professor_first_name: 'Pei-Yu Eric')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C187L', professor_last_name: 'Chen', professor_first_name: 'Yong')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '194', professor_last_name: 'Carman', professor_first_name: 'Gregory')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '231B', professor_last_name: 'Pilon', professor_first_name: 'Laurent')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C232A', professor_last_name: 'Marner', professor_first_name: 'Wilbur J')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '250B', professor_last_name: 'Karagozian', professor_first_name: 'Ann R.')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C250G', professor_last_name: 'Eldredge', professor_first_name: 'Jeff')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C250R', professor_last_name: 'Wirz', professor_first_name: 'Richard')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '255A', professor_last_name: 'Kinsey', professor_first_name: 'Robert')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'M256C', professor_last_name: 'Ju', professor_first_name: 'Jiann-Wen')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '256F', professor_last_name: 'Gupta', professor_first_name: 'Vijay')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '260', professor_last_name: 'Abdou', professor_first_name: 'Mohamed')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'M269A', professor_last_name: 'Zhang', professor_first_name: 'Hao')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '269B', professor_last_name: 'Bendiksen', professor_first_name: 'Oddvar')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '273A', professor_last_name: 'Iwasaki', professor_first_name: 'Tetsuya')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '275A', professor_last_name: 'Gibson', professor_first_name: 'James S.')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'M280B', professor_last_name: 'Candler', professor_first_name: 'Robert')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C286', professor_last_name: 'Chiou', professor_first_name: 'Pei-Yu Eric')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: 'C287L', professor_last_name: 'Chen', professor_first_name: 'Yong')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '297', professor_last_name: 'Yang', professor_first_name: 'Jenn-Ming')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '298', professor_last_name: 'Carman', professor_first_name: 'Gregory')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '298', professor_last_name: 'Li', professor_first_name: 'Xiaochun')
Course.create(department: 'Mechanical And Aerospace Engineering', course_id: '495', professor_last_name: 'Alvarez', professor_first_name: 'Morad')

user = User.create! :email => 'admin@admin.com', :password => 'admin1234', :password_confirmation => 'admin1234', :first_name => 'admin', :last_name => 'admin', :courses_taken => "Computer Science 31, Computer Science 32", :admin => true
# Document.create([{path: '/CS31/COM_SCI_31_Unknown_2010_Fall_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2010_Fall'}, {path: '/CS32/COM_SCI_32_Nachenberg_2012_Winter_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2012_Winter'}, {path: '/CS32/COM_SCI_32_Smallberg_2007_Winter_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2007_Winter'}])
# Document.create([{path: '/CS33/COM_SCI_33_Reinman_2009_Spring_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2009_Spring'}, {path: '/CS33/COM_SCI_33_Reinman_2010_Spring_MT_1.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2010_Spring'}, {path: '/CS33/COM_SCI_33_Rohr_2008_Fall_MT.pdf', uploader_id: "1", doc_type: "Test", quarter_year: '2008_Fall'}])

